// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlbedoProtocol.proto

#include "AlbedoProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace AlbedoProtocol {
}  // namespace AlbedoProtocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_AlbedoProtocol_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_AlbedoProtocol_2eproto = nullptr;
const uint32_t TableStruct_AlbedoProtocol_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_AlbedoProtocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024AlbedoProtocol.proto\022\016AlbedoProtocol*\326"
  "\002\n\003PID\022\n\n\006FAILED\020\000\022\013\n\007SUCCESS\020\001\022\n\n\006RESEN"
  "D\020\002\022\036\n\032REGISTER_PLACEHOLDER_BEGIN\020d\022\024\n\020R"
  "EGISTER_SUCCESS\020e\022\023\n\017REGISTER_FAILED\020f\022 "
  "\n\034REGISTER_CLIENT_SEND_REQUEST\020g\022%\n!REGI"
  "STER_CLIENT_SEND_VERIFICATION\020h\022\034\n\030REGIS"
  "TER_PLACEHOLDER_END\020i\022\033\n\026DOCK_PLACEHOLDE"
  "R_BEGIN\020\350\007\022\024\n\017DOCK_SHAKE_HAND\020\351\007\022\017\n\nDOCK"
  "_ALIVE\020\352\007\022\031\n\024DOCK_SEND_DOCKERLIST\020\353\007\022\031\n\024"
  "DOCK_PLACEHOLDER_END\020\354\007b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_AlbedoProtocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_AlbedoProtocol_2eproto = {
    false, false, 391, descriptor_table_protodef_AlbedoProtocol_2eproto,
    "AlbedoProtocol.proto",
    &descriptor_table_AlbedoProtocol_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_AlbedoProtocol_2eproto::offsets,
    nullptr, file_level_enum_descriptors_AlbedoProtocol_2eproto,
    file_level_service_descriptors_AlbedoProtocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_AlbedoProtocol_2eproto_getter() {
  return &descriptor_table_AlbedoProtocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_AlbedoProtocol_2eproto(&descriptor_table_AlbedoProtocol_2eproto);
namespace AlbedoProtocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PID_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_AlbedoProtocol_2eproto);
  return file_level_enum_descriptors_AlbedoProtocol_2eproto[0];
}
bool PID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 100:
    case 101:
    case 102:
    case 103:
    case 104:
    case 105:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace AlbedoProtocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
