// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dock_protocol.proto

#include "dock_protocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace DockProtocol {
PROTOBUF_CONSTEXPR ShakeHand::ShakeHand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.intro_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.pass_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.limit_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ShakeHandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShakeHandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShakeHandDefaultTypeInternal() {}
  union {
    ShakeHand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShakeHandDefaultTypeInternal _ShakeHand_default_instance_;
PROTOBUF_CONSTEXPR DockerList::DockerList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.dockers_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DockerListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DockerListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DockerListDefaultTypeInternal() {}
  union {
    DockerList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DockerListDefaultTypeInternal _DockerList_default_instance_;
}  // namespace DockProtocol
static ::_pb::Metadata file_level_metadata_dock_5fprotocol_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_dock_5fprotocol_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dock_5fprotocol_2eproto = nullptr;

const uint32_t TableStruct_dock_5fprotocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DockProtocol::ShakeHand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DockProtocol::ShakeHand, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::DockProtocol::ShakeHand, _impl_.intro_),
  PROTOBUF_FIELD_OFFSET(::DockProtocol::ShakeHand, _impl_.pass_),
  PROTOBUF_FIELD_OFFSET(::DockProtocol::ShakeHand, _impl_.limit_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DockProtocol::DockerList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DockProtocol::DockerList, _impl_.dockers_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::DockProtocol::ShakeHand)},
  { 10, -1, -1, sizeof(::DockProtocol::DockerList)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::DockProtocol::_ShakeHand_default_instance_._instance,
  &::DockProtocol::_DockerList_default_instance_._instance,
};

const char descriptor_table_protodef_dock_5fprotocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023dock_protocol.proto\022\014DockProtocol\"E\n\tS"
  "hakeHand\022\014\n\004name\030\001 \001(\t\022\r\n\005intro\030\002 \001(\t\022\014\n"
  "\004pass\030\003 \001(\t\022\r\n\005limit\030\004 \001(\005\"6\n\nDockerList"
  "\022(\n\007dockers\030\001 \003(\0132\027.DockProtocol.ShakeHa"
  "ndb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_dock_5fprotocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dock_5fprotocol_2eproto = {
    false, false, 170, descriptor_table_protodef_dock_5fprotocol_2eproto,
    "dock_protocol.proto",
    &descriptor_table_dock_5fprotocol_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_dock_5fprotocol_2eproto::offsets,
    file_level_metadata_dock_5fprotocol_2eproto, file_level_enum_descriptors_dock_5fprotocol_2eproto,
    file_level_service_descriptors_dock_5fprotocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dock_5fprotocol_2eproto_getter() {
  return &descriptor_table_dock_5fprotocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dock_5fprotocol_2eproto(&descriptor_table_dock_5fprotocol_2eproto);
namespace DockProtocol {

// ===================================================================

class ShakeHand::_Internal {
 public:
};

ShakeHand::ShakeHand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DockProtocol.ShakeHand)
}
ShakeHand::ShakeHand(const ShakeHand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ShakeHand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.intro_){}
    , decltype(_impl_.pass_){}
    , decltype(_impl_.limit_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.intro_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.intro_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_intro().empty()) {
    _this->_impl_.intro_.Set(from._internal_intro(), 
      _this->GetArenaForAllocation());
  }
  _impl_.pass_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pass_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_pass().empty()) {
    _this->_impl_.pass_.Set(from._internal_pass(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.limit_ = from._impl_.limit_;
  // @@protoc_insertion_point(copy_constructor:DockProtocol.ShakeHand)
}

inline void ShakeHand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.intro_){}
    , decltype(_impl_.pass_){}
    , decltype(_impl_.limit_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.intro_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.intro_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pass_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pass_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ShakeHand::~ShakeHand() {
  // @@protoc_insertion_point(destructor:DockProtocol.ShakeHand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ShakeHand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.intro_.Destroy();
  _impl_.pass_.Destroy();
}

void ShakeHand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ShakeHand::Clear() {
// @@protoc_insertion_point(message_clear_start:DockProtocol.ShakeHand)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.intro_.ClearToEmpty();
  _impl_.pass_.ClearToEmpty();
  _impl_.limit_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ShakeHand::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DockProtocol.ShakeHand.name"));
        } else
          goto handle_unusual;
        continue;
      // string intro = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_intro();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DockProtocol.ShakeHand.intro"));
        } else
          goto handle_unusual;
        continue;
      // string pass = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_pass();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DockProtocol.ShakeHand.pass"));
        } else
          goto handle_unusual;
        continue;
      // int32 limit = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.limit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ShakeHand::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DockProtocol.ShakeHand)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DockProtocol.ShakeHand.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string intro = 2;
  if (!this->_internal_intro().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_intro().data(), static_cast<int>(this->_internal_intro().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DockProtocol.ShakeHand.intro");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_intro(), target);
  }

  // string pass = 3;
  if (!this->_internal_pass().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pass().data(), static_cast<int>(this->_internal_pass().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DockProtocol.ShakeHand.pass");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_pass(), target);
  }

  // int32 limit = 4;
  if (this->_internal_limit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_limit(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DockProtocol.ShakeHand)
  return target;
}

size_t ShakeHand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DockProtocol.ShakeHand)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string intro = 2;
  if (!this->_internal_intro().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_intro());
  }

  // string pass = 3;
  if (!this->_internal_pass().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pass());
  }

  // int32 limit = 4;
  if (this->_internal_limit() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_limit());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ShakeHand::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ShakeHand::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ShakeHand::GetClassData() const { return &_class_data_; }


void ShakeHand::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ShakeHand*>(&to_msg);
  auto& from = static_cast<const ShakeHand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DockProtocol.ShakeHand)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_intro().empty()) {
    _this->_internal_set_intro(from._internal_intro());
  }
  if (!from._internal_pass().empty()) {
    _this->_internal_set_pass(from._internal_pass());
  }
  if (from._internal_limit() != 0) {
    _this->_internal_set_limit(from._internal_limit());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ShakeHand::CopyFrom(const ShakeHand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DockProtocol.ShakeHand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShakeHand::IsInitialized() const {
  return true;
}

void ShakeHand::InternalSwap(ShakeHand* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.intro_, lhs_arena,
      &other->_impl_.intro_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.pass_, lhs_arena,
      &other->_impl_.pass_, rhs_arena
  );
  swap(_impl_.limit_, other->_impl_.limit_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ShakeHand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dock_5fprotocol_2eproto_getter, &descriptor_table_dock_5fprotocol_2eproto_once,
      file_level_metadata_dock_5fprotocol_2eproto[0]);
}

// ===================================================================

class DockerList::_Internal {
 public:
};

DockerList::DockerList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DockProtocol.DockerList)
}
DockerList::DockerList(const DockerList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DockerList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.dockers_){from._impl_.dockers_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:DockProtocol.DockerList)
}

inline void DockerList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.dockers_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DockerList::~DockerList() {
  // @@protoc_insertion_point(destructor:DockProtocol.DockerList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DockerList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.dockers_.~RepeatedPtrField();
}

void DockerList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DockerList::Clear() {
// @@protoc_insertion_point(message_clear_start:DockProtocol.DockerList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.dockers_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DockerList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .DockProtocol.ShakeHand dockers = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_dockers(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DockerList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DockProtocol.DockerList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .DockProtocol.ShakeHand dockers = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_dockers_size()); i < n; i++) {
    const auto& repfield = this->_internal_dockers(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DockProtocol.DockerList)
  return target;
}

size_t DockerList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DockProtocol.DockerList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .DockProtocol.ShakeHand dockers = 1;
  total_size += 1UL * this->_internal_dockers_size();
  for (const auto& msg : this->_impl_.dockers_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DockerList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DockerList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DockerList::GetClassData() const { return &_class_data_; }


void DockerList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DockerList*>(&to_msg);
  auto& from = static_cast<const DockerList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DockProtocol.DockerList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.dockers_.MergeFrom(from._impl_.dockers_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DockerList::CopyFrom(const DockerList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DockProtocol.DockerList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DockerList::IsInitialized() const {
  return true;
}

void DockerList::InternalSwap(DockerList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.dockers_.InternalSwap(&other->_impl_.dockers_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DockerList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dock_5fprotocol_2eproto_getter, &descriptor_table_dock_5fprotocol_2eproto_once,
      file_level_metadata_dock_5fprotocol_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace DockProtocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::DockProtocol::ShakeHand*
Arena::CreateMaybeMessage< ::DockProtocol::ShakeHand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DockProtocol::ShakeHand >(arena);
}
template<> PROTOBUF_NOINLINE ::DockProtocol::DockerList*
Arena::CreateMaybeMessage< ::DockProtocol::DockerList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DockProtocol::DockerList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
