// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_type.proto

#include "message_type.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

static const ::_pb::EnumDescriptor* file_level_enum_descriptors_message_5ftype_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_message_5ftype_2eproto = nullptr;
const uint32_t TableStruct_message_5ftype_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_message_5ftype_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022message_type.proto*I\n\013MessageType\022\n\n\006f"
  "ailed\020\000\022\013\n\007success\020\001\022\014\n\010register\020\002\022\t\n\005lo"
  "gin\020\003\022\010\n\004exit\020\004b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_message_5ftype_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_message_5ftype_2eproto = {
    false, false, 103, descriptor_table_protodef_message_5ftype_2eproto,
    "message_type.proto",
    &descriptor_table_message_5ftype_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_message_5ftype_2eproto::offsets,
    nullptr, file_level_enum_descriptors_message_5ftype_2eproto,
    file_level_service_descriptors_message_5ftype_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_message_5ftype_2eproto_getter() {
  return &descriptor_table_message_5ftype_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_message_5ftype_2eproto(&descriptor_table_message_5ftype_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_message_5ftype_2eproto);
  return file_level_enum_descriptors_message_5ftype_2eproto[0];
}
bool MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
